"""strava_auth_json added

Revision ID: 2d4d127afc94
Revises: e1f50c976f73
Create Date: 2020-07-23 17:20:27.063600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4d127afc94'
down_revision = 'e1f50c976f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('strava_auth_json', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'strava_auth_json')
    # ### end Alembic commands ###
