"""strava_athlete_json

Revision ID: e13579b374ae
Revises: 2d4d127afc94
Create Date: 2020-07-23 17:56:47.817171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13579b374ae'
down_revision = '2d4d127afc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('strava_athlete_json', sa.String(), nullable=True))
    op.drop_column('user', 'strava_auth_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('strava_auth_json', sa.BLOB(), nullable=True))
    op.drop_column('user', 'strava_athlete_json')
    # ### end Alembic commands ###
